_BASE_: ../R50_bs16_50ep.yaml
MODEL:
  BACKBONE:
    NAME: "DPT_DINOv2"
  DINOv2:
    ENCODER: 'vits'
    NCLASS: 1
    FEATURES: 256
    OUT_CHANNELS: [128, 256, 512, 1024]
    USE_BN: False
    USE_CLSTOKEN: False
    LOCALHUB: True
  SEM_SEG_HEAD:
    PIXEL_DECODER_NAME: "DPTDecoder"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  MASK_FORMER:
    SIZE_DIVISIBILITY: 14
